list_devices:
  name: List Alexa devices
  description: Lists all available Alexa devices.
  fields: {}

delete_device:
  name: Delete Alexa device
  description: Deletes an Alexa device by device ID.
  fields:
    device_id:
      required: true
      selector:
        text:
